export const AppConfig = {
	site_name: 'Bruhhou.se',
	title: "Safe's Template Editor",
	description: 'Contact me if you need help',
	locale: 'en',
};

export const Globals = {
	watermark:
		'GENERATED BY @SAFE HTTPS://TOYHOU.SE/SAFE || TEMPLATES GIVEN WITH EXPLICIT PERMISSION BY AUTHOR. ALL RIGHTS RESERVED.',
};
